language: python

python:
 - "3.6"

env:
  global:
   - DOWNLOADS=$HOME/downloads
   - HTML_PATH=$TRAVIS_BUILD_DIR/docs/build/html

cache: 
 - directories:
   - $DOWNLOADS
   - $HOME/.cache/pip

before_install:
 # create display with large resolution
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
 - python setup_wonambi.py --get_files

install: 
 # install conda / python (opengl doesn't work with pip)
 - wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - chmod +x miniconda.sh
 - conda config --set always_yes yes --set changeps1 no
 - conda update -q conda
 - conda info -a

 # install requirements
 - conda create -q -n full-environment numpy scipy pyqt
 - source activate full-environment
 - pip install nibabel vispy h5py
 - pip install pytest pytest-qt pytest-cov codecov plotly
 - pip install sphinx sphinx_rtd_theme
 - pip install -e .

before_script:
  - "export DISPLAY=:99.0"

script:
 - python -c "import vispy; print(vispy.sys_info()); exit()"
 - python setup_wonambi.py --tests

 # test without optional requirements (append .coverage)
 - source deactivate
 - pip install numpy scipy
 - pip install pytest pytest-cov codecov
 - python setup_wonambi.py --test_import

 # use all optional requirements for docs
 - source activate full-environment
 - python setup_wonambi.py --docs

after_success:
 - codecov

notifications:
 email: false

deploy:
 - provider: pages
   skip_cleanup: true
   target_branch : master
   local_dir : $HTML_PATH
   repo : wonambi-python/wonambi-python.github.io
   github_token : $GITHUB_TOKEN
 - provider: pypi
   user: $PYPI_USER
   password: $PYPI_PASSWORD
   on:
     tags: true
